#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Wed Nov 02 16:13:59 CST 2016
apiSecret=54218fc40c68765eb17f34e3d4289bbbf52ae89de589f396440e9684238d2ee5
